### PR TITLE
fix(profile-page): Fix errors & UI on profile page without survey results

### LINKED ISSUE #195: bug(profile-page): Improve UI when the current survey hasn't been filled out yet
Image

### PR DESCRIPTION
**Pull request by Andreas02-dev**
image

Closes #195

### CODE REVIEW

File: src/app/find-the-expert/profile-page/page.tsx [hunk 1]
```diff
@@ -154,7 +154,13 @@ const ProfilePage = async ({
                         )}
                     </div>
                 </h3>
-                <h3 className="mb-2 text-center text-lg font-semibold">
+                {(user.communicationPreferences === null ||
+                    user.communicationPreferences!.methods.length === 0) && (
+                    <p className="text-center">
+                        No communication methods selected.
```
Comment (jellebuitenhuisis) [inline src/app/find-the-expert/profile-page/page.tsx:160]: In other places in the application we use "Do not contact"

**Review by jellebuitenhuisis — CHANGES_REQUESTED** [review]

**Review by jellebuitenhuisis — APPROVED** [review]
